language: node_js

node_js:
  - 11

branches:
  only:
    - master
    - "/^travis-.*$/"

services:
  - docker

before_install:
  # Install dependencies
  - gem update --system
  - npm install
  - npm run build
  # Other jobs to prepare your environment
  # like AWS settings, GCP settings, etc
  - docker info
  - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_LOGIN --password-stdin

install:
  - docker build -t polzka90/dicountdocker .

script: "true"

after_success:
  # Scripts to tag and push images to docker hub
  # Scripts to deploy to cloud service like GCP, AWS, Azure, etc
